### ISSUE TITLE
CronJob spec not quite there

### ISSUE THREAD

**Issue by szinn** [bjw-s/helm-charts#111]
# Details

Saw that the app-template can create a cron-job resource, so I gave it a try and it didn't get a few things.

values.yaml
```
    controller:
      type: cronjob
      cronjob:
        schedule: "@daily"
        ttlSecondsAfterFinished: 43200
    restartPolicy: OnFailure
    image:
      repository: docker.io/prodrigestivill/postgres-backup-local
      tag: 15@sha256:93f597a7ad95d5a9d988e57c32442e6f78d6e88d809ca96bb0a3270e45c85650
      pullPolicy: IfNotPresent
    command: ["/backup.sh"]
    env:
      - name: POSTGRES_HOST
        value: postgres-ro.dbms.svc.cluster.local
      - name: POSTGRES_USER
        valueFrom:
          secretKeyRef:
            name: postgres-superuser
            key: POSTGRES_SUPER_USER
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: postgres-superuser
            key: POSTGRES_SUPER_PASS
      - name: POSTGRES_DB
        value: "outline,shlink,teslamate"
      - name: BACKUP_KEEP_DAYS
        value: "7"
      - name: BACKUP_KEEP_WEEKS
        value: "4"
      - name: BACKUP_KEEP_MONTHS
        value: "6"
      - name: BACKUP_KEEP_MINS
        value: "1440"
      - name: POSTGRES_EXTRA_OPTS
        value: "-b -C -Z6"
    enableServiceLinks: false
    service:
      main:
        enabled: false
    persistence:
      backups:
        enabled: true
        existingClaim: postgres-backups
        mountPath: /backups
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
```

output.yaml
```
---
# Source: app-template/templates/common.yaml
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  labels:
    app.kubernetes.io/instance: postgres-backup
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgres-backup
    helm.sh/chart: app-template-1.2.1
spec:
  concurrencyPolicy: "Forbid"
  startingDeadlineSeconds: 30
  schedule: "@daily"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 43200
      template:
        metadata:
          labels:
            app.kubernetes.io/name: postgres-backup
            app.kubernetes.io/instance: postgres-backup
        spec:
          
          serviceAccountName: default
          automountServiceAccountToken: true
          securityContext:
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 568
            runAsUser: 568
          dnsPolicy: ClusterFirst
          enableServiceLinks: false
          containers:
            - name: postgres-backup
              image: "docker.io/prodrigestivill/postgres-backup-local:15@sha256:93f597a7ad95d5a9d988e57c32442e6f78d6e88d809ca96bb0a3270e45c85650"
              imagePullPolicy: IfNotPresent
              command:
                  
                - /backup.sh
              env:
                - name: POSTGRES_HOST
                  value: postgres-ro.dbms.svc.cluster.local
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      key: POSTGRES_SUPER_USER
                      name: postgres-superuser
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: POSTGRES_SUPER_PASS
                      name: postgres-superuser
                - name: POSTGRES_DB
                  value: outline,shlink,teslamate
                - name: BACKUP_KEEP_DAYS
                  value: "7"
                - name: BACKUP_KEEP_WEEKS
                  value: "4"
                - name: BACKUP_KEEP_MONTHS
                  value: "6"
                - name: BACKUP_KEEP_MINS
                  value: "1440"
                - name: POSTGRES_EXTRA_OPTS
                  value: -b -C -Z6
              ports:
                
              volumeMounts:
                - name: backups
                  mountPath: /backups
              livenessProbe:
              readinessProbe:
              startupProbe:
          volumes:
            - name: backups
              persistentVolumeClaim:
                claimName: postgres-backups
          restartPolicy: Never
```

command:
```
helm template postgres-backup -n dbms bjw-s/app-template -f values.yaml > output.yaml
```

**What did you expect to happen:**

The `ports:` entry shouldn't be present because there aren't any ports.

As well, the livenessProbe, readinessProbe, and startupProbe are specified but don't have any defaults. (or shouldn't be there)

**Anything else you would like to add:**

Not sure if this is a desired use of the template at all, but it did work for recyclarr (from Devin of course)

**Additional Information:**
