### ISSUE TITLE
Preserve order of `initContainers`

### ISSUE THREAD

**Issue by onedr0p** [bjw-s/helm-charts#122]
# Details

**What steps did you take and what happened:**

It looks like `initContainers` ordering is not preserved when the values are templated out.

https://github.com/onedr0p/home-ops/blob/576dd2ccee7de3351e6e648ad868189f755c15d2/kubernetes/apps/default/guacamole/app/guacamole/helmrelease.yaml#L33-L65

This gets templated out like

```yaml
      initContainers:
      - args:
        - -c
        - |
          /opt/guacamole/bin/initdb.sh --postgres > /migrations/init.sql
        command:
        - /bin/sh
        envFrom:
        - secretRef:
            name: guacamole-secret
        image: docker.io/guacamole/guacamole:1.5.0
        imagePullPolicy: IfNotPresent
        name: create-schema
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /migrations
          name: migrations
      - envFrom:
        - secretRef:
            name: guacamole-secret
        image: ghcr.io/onedr0p/postgres-initdb:14.6
        imagePullPolicy: IfNotPresent
        name: init-db
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - args:
        - -c
        - |
          export PGPASSWORD=$(POSTGRES_PASSWORD)
          psql -h $(POSTGRES_HOSTNAME) -d $(POSTGRES_DATABASE) -U $(POSTGRES_USER) -a -w -f /migrations/init.sql || true
        command:
        - /bin/bash
        envFrom:
        - secretRef:
            name: guacamole-secret
        image: ghcr.io/onedr0p/postgres-initdb:14.6
        imagePullPolicy: IfNotPresent
        name: run-migrations
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /migrations
          name: migrations
```

It is my understanding that initContainers run in the order specified.
