### ISSUE TITLE
Support for prometheusRule

### ISSUE THREAD

**Issue by reefland** [bjw-s/helm-charts#133]
# Details

I would like the common chart to be able to support `prometheusRule`, which goes nicely with the existing `serviceMonitor`. 

Example:
```
# -- Enable and configure Prometheus Rules for the chart under this key.
prometheusRule:
  enabled: true
  labels: {}
  # -- Configure additionial rules for the chart under this key.
  rules:
    - alert: SonarrDown
      annotations:
      description: Sonarr service is down.
      summary: Sonarr is down.
      expr: |
        sonarr_system_status == 0
        for: 5m
        labels:
          severity: critical
```

**Anything else you would like to add:**

**Additional Information:**
