### ISSUE TITLE
RFC: Add basic serviceMonitor support into library chart

### ISSUE THREAD

**Issue by onedr0p** [bjw-s/helm-charts#15]
# Details

**Describe the solution you'd like:**

Using the library chart with applications that export metrics requires the user to write a separate `serviceMonitor` manifests.

Add basic support for embedding a `serviceMonitor` in the library chart

For example:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app cloudflare-exporter
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: kah-common-chart
      version: 1.2.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    global:
      nameOverride: *app
    controller:
      strategy: RollingUpdate
    image:
      repository: ghcr.io/lablabs/cloudflare_exporter
      tag: 0.0.13
    env:
      FREE_TIER: "true"
    envFrom:
      - secretRef:
          name: *app
    service:
      main:
        ports:
          http:
            port: 8080
    # Full Options for Service Monitor
    serviceMonitor:
      enabled: true
      endpoints:
        - port: http
          path: /metrics
          interval: 1m
          scrapeTimeout: 10s
```

Open to any thoughts on this, maybe we pass the full `spec` thru to the `serviceMonitor` omitting the `spec.selector` which can be auto populated?

```yaml
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: &app cloudflare-exporter
  namespace: monitoring
  labels: &labels
    app.kubernetes.io/instance: *app
    app.kubernetes.io/name: *app
spec:
  selector:
    matchLabels:
      <<: *labels
  endpoints:
    - port: http
      scheme: http
      path: /metrics
      interval: 1m
      scrapeTimeout: 10s
```

**Comment by reefland** [comment]
Not clear to me, where you would place the `release: kube-prometheus-stack` type label needed for auto-discovery?

Would this work???
```
    # Full Options for Service Monitor
    serviceMonitor:
      enabled: true
      endpoints:
        - port: http
          path: /metrics
          interval: 1m
          scrapeTimeout: 10s
      # -- Additional labels for the Kubernetes `ServiceMonitor` object
      labels:
        release: kube-prometheus-stack
```

Side note - can you also consider creating a podMonitor equivalent? If the pod doesn't require a service in front of it, then no reason to create one just for the sake of using a serviceMonitor.
