### ISSUE TITLE
Support for Argo Rollouts Controller

### ISSUE THREAD

**Issue by zodiac12k** [bjw-s/helm-charts#154]
# Details

Is it possible to support for argo rollouts controller?

> Argo Rollouts is a [Kubernetes controller](https://kubernetes.io/docs/concepts/architecture/controller/) and set of [CRDs](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/) which provide advanced deployment capabilities such as blue-green, canary, canary analysis, experimentation, and progressive delivery features to Kubernetes.

**Describe the solution you'd like:**

Example: 
```
controller:
  type: rollout

  rollout:
    strategy:
      canary:
        # Reference to a Service which the controller will update to point to the canary ReplicaSet
        canaryService: rollouts-demo-canary
        # Reference to a Service which the controller will update to point to the stable ReplicaSet
        stableService: rollouts-demo-stable
        trafficRouting:
          nginx:
            # Reference to an Ingress which has a rule pointing to the stable service (e.g. rollouts-demo-stable)
            # This ingress will be cloned with a new name, in order to achieve NGINX traffic splitting.
            stableIngress: rollouts-demo-stable
```

**Anything else you would like to add:**

**Additional Information:**
