### ISSUE TITLE
Add support for networkpolicy

### ISSUE THREAD

**Issue by dani-CO-CN** [bjw-s/helm-charts#156]
# Details

**Describe the solution you'd like:**

I could not find a way to add fully fledged networkpolicies (ingress/egress) to my workload. 

**Anything else you would like to add:**

I found a way to deploy egress network policies by "hacking" them into the vpn addon, unfortunately it is only possible to add egress policies.

```yaml
addons:
  vpn:
    enabled: true
    type: ""
    networkPolicy:
      enabled: true
      egress:
      - to:
        - ipBlock:
            cidr: 0.0.0.0/0
```

This config allowed me to get egress network policies, but  unfortunately no ingress

**Additional Information:**

I would be interested in implementing this feature. Thank you for this great helm chart 🥳🙏
