### ISSUE TITLE
Don't sort env variables

### ISSUE THREAD

**Issue by dani-CO-CN** [bjw-s/helm-charts#160]
# Details

**What steps did you take and what happened:**

use the app-template with the env vars:

```yaml
env:
  # -- Config dir
  DATA_FOLDER: "config"
  A_FOLDER: "sometest"
```
This will lead to a e.g. deployment with:
```yaml
env:
  - name: A_FOLDER
    value: sometest
  - name: DATA_FOLDER
    value: config
```
Env var sorting breaks [dependent environment variables of kubernetes](https://kubernetes.io/docs/tasks/inject-data-application/define-interdependent-environment-variables/). 

**What did you expect to happen:**

Don't change the order of env vars.

**Anything else you would like to add:**

**Additional Information:**
