### ISSUE TITLE
Support mulitline stringData secret

### ISSUE THREAD

**Issue by dani-CO-CN** [bjw-s/helm-charts#161]
# Details

**What steps did you take and what happened:**

Inject a x509 certificate as stringData for a secret. I tried multiple yaml formatters but failed (`|` or `|-`)
```yaml
secrets:
  secret:
    enabled: true
    stringData: |-
      aldfaldflaf
      adfadfadf
```

**What did you expect to happen:**

That the secret just has a literal block with 

```yaml
stringData: |-
    aldfaldflaf
    adfadfadf
```

but instead it is rendered as

```yaml
stringData:
  |-
    aldfaldflaf
    adfadfadf
```

**Anything else you would like to add:**

**Additional Information:**

**Comment by bjw-s** [comment]
Thanks for the bug report! I'll look in to it and see about fixing it

**Comment by bjw-s** [comment]
I took some time to look at this, and this isn't actually a bug... Kubernetes expects key-value pairs for the `stringData` field so the correct syntax for `stringData` would be this:

```yaml
secrets:
  secret:
    enabled: true
    stringData:
      secret.crt: |-
        aldfaldflaf
        adfadfadf
```
