### ISSUE TITLE
"ports" property missing under main container in new version 2.0.1

### ISSUE THREAD

**Issue by runenielsen** [bjw-s/helm-charts#197]
# Details

This is primarily a question to know ensure that the change below was intentional and hear the reasoning, not necessarily a bug.

I upgraded my Helm chart from using version 1.5.1 to 2.0.1 and compared the rendered result.

Previously I automatically got a `ports` property under the main container in the rendered result, like this:

```
    spec:
...
      containers:
        - name: ...
...
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
```

... in the new version I have to add it myself manually in my values-file, like this:

```
controllers:
  main:
    containers:
      main:
...
        ports:
          - containerPort: 8080
            name: http
            protocol: TCP
```

... otherwise it is not rendered. Was this change on purpose, and what is the reason?

**What did you expect to happen:**

I expected the new version to render the same as the old version for `ports`, but I'm no charting expert, so there is probably a reason for the change, that I am not aware of.

**Anything else you would like to add:**

No.

**Additional Information:**

No.
