### ISSUE TITLE
When using Route.main.hostnames with templated values it returns an error

### ISSUE THREAD

**Issue by snoopy82481** [bjw-s/helm-charts#211]
# Details

**What steps did you take and what happened:**

When using the following configuration the value for Release.Name is not replaced in the hostnames section
```yaml
route:
  main:
    enabled: true
    parentRefs:
      - name: cilium-internal
        namespace: networking
        sectionName: *app
    hostnames:
      - "{{ .Release.Name }}.${SECRET_DOMAIN}"
    rules:
      backendRefs:
        - port: http
```

**What did you expect to happen:**

I expected the `Release.Name` to be replaced when installing/upgrading deployment.

**Anything else you would like to add:**

Variable substitutions still works so the `${SECRET_DOMAIN}` is replaced.

**Additional Information:**
