### ISSUE TITLE
ConfigMaps Seem To Not Be Created With v2 Of The Template

### ISSUE THREAD

**Issue by TheDarkula** [bjw-s/helm-charts#225]
First off, thank you so much for all of your work!

The v2 template is very nice :)

I have run into an issue using configmaps, though.

Using the example from the values file [here](https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml#L374C1-L385C17), I have this yaml block:

```
configMaps:
  config-yaml:
    enabled: true
    labels: {}
    annotations: {}
    data:
      file.yaml: |
        data goes here
```

However, in the new version of the template, a configmap is not created.

Am I missing something here?
