### ISSUE TITLE
initContainer tag being truncated in v2.3.0

### ISSUE THREAD

**Issue by adampetrovic** [bjw-s/helm-charts#229]
# Details

**What steps did you take and what happened:**

Upgrading my application which makes use of initContainers from app-template 1.x to 2.3.0. In doing so, I have the image ghcr.io/onedr0p/postgres-init:14.10.

When I deploy, the init container is created with image tag `14.1` instead of `14.10`, causing the container to fail as that version doesn't exist.

**What did you expect to happen:**

I expect the initContainer to use the image tag specified.

**Additional Information:**

configuration:
```
 controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 14.10
              pullPolicy: Always
            envFrom:
              - secretRef:
                  name: teslamate-secret
```

resulting deployment:
```
Init Containers:
   init-db:
    Image:      ghcr.io/onedr0p/postgres-init:14.1
    Port:       <none>
    Host Port:  <none>
```
