### ISSUE TITLE
securityContext capabilities is not supported by schema

### ISSUE THREAD

**Issue by evanrich** [bjw-s/helm-charts#236]
```
Failed to compare desired state to live state: failed to calculate diff: error calculating structured merge diff: error building typed value from config resource: .spec.template.spec.securityContext.capabilities: field not declared in schema
```

I get the above message when trying to do the following with the 2.3.0 version of the chart:
```
defaultPodOptions:
  securityContext:
    capabilities:
      drop:
        - all
      add: ['NET_BIND_SERVICE']
```

it seems that defaultPodOptions.securityContext is supported, but not capabilities.  When I look at the common chart, it just shows

```
  # -- Configure the Security Context for the Pod
  securityContext: {}
```
and no example.  Is this not supported?
