### ISSUE TITLE
podDefaults.imagePullSecrets not setting secrets

### ISSUE THREAD

**Issue by brandan-schmitz** [bjw-s/helm-charts#243]
# Details

**What steps did you take and what happened:**
I built a deployment using the app-template chart and supplied the imagePullSecrets under the defaultPodOptions section and when the helm chart was deployed it did not add the secrets to the pod. The running pod YAML has no mention of the image pull secrets.

**What did you expect to happen:**
I would have expected the imagePullSecrets to be present in the pod that was rendered and deployed.

**Anything else you would like to add:**
I have been able to get around the issue by adding the imagePullSecrets section to the pod key under the container in the controllers section.

**Additional Information:**
The following values is not working.
```yaml
defaultPodOptions:
  imagePullSecrets:
    - name: my-secret-name
```

However the following would work:
```yaml
controllers:
  main:
    containers:
      main:
        pod:
          imagePullSecrets:
            - name: my-secret-name
```
