### ISSUE TITLE
Define multiple services for single container

### ISSUE THREAD

**Issue by epcim** [bjw-s/helm-charts#263]
# Details

**Describe the solution you'd like:**

In the past v1.5.1 etc.. charts it was possible define services/ports/loadbalanncers independently from images, ie, for example Syncthing could run one container (listening on 6 ports), but I could define each service independently (some exposed as TCP some as UDP (on different IP, which in fact is required at some cases - ie: with traefik LB)

with 2.x.x I would like to do still this (while having in controllers: only single image):
```
  service:
    main:
      ports:
        http:
          port: 8384
    listen:
      enabled: true
      type: LoadBalancer
      # https://kubernetes.io/docs/tutorials/services/source-ip/
      externalTrafficPolicy: Local # Cluster
      ports:
        listen:
          enabled: true
          port: 22000
          protocol: TCP
          targetPort: 22000
    discovery:
      enabled: true
      type: LoadBalancer
      externalTrafficPolicy: Local # Cluster
      ports:
        discovery:
          enabled: true
          port: 21027
          protocol: UDP
          targetPort: 21027
```

**Anything else you would like to add:**

Current error, if spec under controllers is not specified:
```
✗ Rendering Helm Charts
✗ 1 error occurred:
        * rendering helm chart app-template for release syncthing has failed: execution error at (app-template/templates/common.yaml:14:3): controller field is required for Service. (service: listen)

```

**Additional Information:**

n/a

**Comment by n0rad** [comment]
```
service:
  XXX:
    controller: main
  YYY:
    controller: main
```
?
