### ISSUE TITLE
Unable to mount hostPaths to a different path in the container

### ISSUE THREAD

**Issue by lkshrk** [bjw-s/helm-charts#277]
# Details

**What steps did you take and what happened:**

`values.yaml:`
```yaml
prowlarr:
  env:
    TZ: Europe/Berlin
  envFrom:
  - configMapRef:
      name: prowlarr-config
  persistence:
    config:
      enabled: true
      type: hostPath
      hostPath: /mnt/config/arr/prowlarr
      hostPathType: Directory
      globalMounts:
      - path: /config
```

extract from the pod definition:
```yaml
volumeMounts:
    - mountPath: /mnt/config/arr/prowlarr
      name: config
...
volumes:
  - hostPath:
      path: /mnt/config/arr/prowlarr
      type: Directory
    name: config
```

**What did you expect to happen:**

I would expect the hostPath `/mnt/config/arr/prowlarr` to be mounted under `/config`, instead it's mounted under `/mnt/config/arr/prowlarr`

**Anything else you would like to add:**

version: ghcr.io/onedr0p/prowlarr-develop:1.14.0.4286

**Additional Information:**

**Comment by bjw-s** [comment]
Thanks for raising the issue. Which version of the chart are you using, as I haven't really been able to reproduce this. I even checked, and there is an explicit test present for this scenario:
https://github.com/bjw-s/helm-charts/blob/main/charts/library/common-test/tests/container/volumemounts_test.yaml#L163-L181

**Comment by TheDarkula** [comment]
I am not sure if this is related, but using version 3.0.2 of the app-template seems to have an issue with `hostPath` storage.

I have the following block:

```
persistence:
  config:
    enabled: true
    type: hostPath
    hostPath: /path/on/host
    accessMode: ReadWriteOnce
    size: 1Gi
    retain: true
    advancedMounts:
      main:
        main:
          - path: /path/in/container
```

Which gives these errors:

```
- persistence.config: Must validate one and only one schema (oneOf)
- persistence.config: Additional property hostPath is not allowed
- persistence.config.type: persistence.config.type does not match: "persistentVolumeClaim"
```
