### ISSUE TITLE
Probe ports chosen from services at random

### ISSUE THREAD

**Issue by gabe565** [bjw-s/helm-charts#289]
# Details

**What steps did you take and what happened:**
I am upgrading all of my HelmReleases to v3 (loving the new JSON schema btw!), and have noticed probe ports seem to be chosen from a random service, and don't match between consecutive calls to `helm template`. I know `port` is an option, but in the past these seemed to be chosen from the `main` service.

**What did you expect to happen:**
I'd probably expect probe ports to be chosen from the current controller's service.

**Anything else you would like to add:**

**Additional Information:**

<details>
  <summary>Repro values.yaml</summary>

If you run
```shell
helm template home-assistant bjw-s/app-template --values app-template-port-bug.yaml
```
with the following `values.yaml`:
```yaml
controllers:
  home-assistant:
    containers:
      app:
        image:
          repository: ghcr.io/home-assistant/home-assistant
          tag: 2024.3.0
        probes: &probes
          startup:
            enabled: true
          liveness:
            enabled: true
          readiness:
            enabled: true
  code:
    containers:
      app:
        image:
          repository: ghcr.io/coder/code-server
          tag: 4.22.0
        args:
          - --disable-telemetry
          - --disable-update-check
          - --auth=none
          - --user-data-dir=/config/.vscode
          - /config
        probes: *probes

service:
  home-assistant:
    controller: main
    ports:
      http:
        port: 8123
  code:
    controller: code
    ports:
      http:
        port: 8080
```
The probes will randomly choose `8080` or `8123`, and don't seem to match between consecutive runs.

```yaml
# ...
           livenessProbe:
             failureThreshold: 3
             initialDelaySeconds: 0
             periodSeconds: 10
             tcpSocket:
               port: 8123
             timeoutSeconds: 1
           name: app
           readinessProbe:
             failureThreshold: 3
             initialDelaySeconds: 0
             periodSeconds: 10
             tcpSocket:
               port: 8080
             timeoutSeconds: 1
           startupProbe:
             failureThreshold: 3
             initialDelaySeconds: 0
             periodSeconds: 10
             tcpSocket:
               port: 8080
             timeoutSeconds: 1
# ...

```
</details>
