### ISSUE TITLE
Add support for `resourceFieldRef` in env `valuesFrom`

### ISSUE THREAD

**Issue by onedr0p** [bjw-s/helm-charts#297]
# Details

**Describe the solution you'd like:**

https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/#store-container-fields

I would like to be able to do something like this:

```yaml
        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/qbittorrent-beta
              tag: 4.6.3@sha256:8e6626727f9f14a3a7909850c40c13e50550bd64cbb3177d8806f0225e57654a
            env:
              QBT_Application__MemoryWorkingSetLimit:
                valueFrom:
                  resourceFieldRef:
                    containerName: app
                    resource: limits.memory
                    divisor: 1Mi
...
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 8152Mi
```
