### ISSUE TITLE
Role and RoleBinding support

### ISSUE THREAD

**Issue by JuniorJPDJ** [bjw-s/helm-charts#305]
# Details

**Describe the solution you'd like:**

Support for creating Role and assigning this role to ServiceAccount using RoleBinding

**Additional Information:**

This is handy with some pre-install/pre-upgrade jobs initializing secrets/configMaps

**Comment by onedr0p** [comment]
This could be solved by https://github.com/bjw-s/helm-charts/issues/314 maybe?

**Comment by JuniorJPDJ** [comment]
Not really, as I'm not talking about app-template, just about the common library. I'm anyway writing own chart using the library so I can add role myself using normal templates. Roles are pretty much common tho so I was thinking that adding those to the library for ease of use would be cool.

**Comment by bjw-s** [comment]
I'm definitely open to adding it, I'm just not sure (yet) what the cleanest way of exposing it through the `values.yaml` would be. Currently thinking of something like this:

```yaml
roles:
  blah:
    clusterWide: false
    rules:
      - apiGroups:
        - ""
        resources:
          - pods
        verbs:
          - get

roleBindings:
  blah:
    clusterWide: false
    roleRef:
      kind: Role
      identifier: blah
      # name: optional role name instead of identifier
    subjects:
      - kind: User
        name: bjw-s
```
