### ISSUE TITLE
port is required when set the enabled to false.

### ISSUE THREAD

**Issue by retX0** [bjw-s/helm-charts#306]
# Details

**What steps did you take and what happened:**
```yaml
app-template:
  service:
    main:
      controller: main
      ports:
        http:
          enabled: false
```

**What did you expect to happen:**

the port only required when enabled = true
