### ISSUE TITLE
Can't assign existing PVC to custom path on the container

### ISSUE THREAD

**Issue by p4block** [bjw-s/helm-charts#327]
# Details
I need to assign a pvc to a /long/path on the host, but it looks like I can't

**What steps did you take and what happened:**

```
persistence:
  data:
    enabled: true
    existingClaim: some-pvc
    globalMounts:
    - path: /foo/bar
      readOnly: false
```

**What did you expect to happen:**

I assumed this would mount the PVC to `/foo/bar`, but it mounts it to `/data`. In fact, no matter what I put in there, the final yaml doesn't change.

I've read the docs and really think this should be working and it's intended, but isn't. Maybe it's because I am using existingClaim.

it's also completely likely I am missing something very obvious

(And I can't simply change the "data" key as workaround because / isn't an allowed character in a volume name)

**Anything else you would like to add:**

If it's possible, maybe we can add it to the example values.yaml. I found nothing of the sort there, but I did on the html docs.
