### ISSUE TITLE
Add support for secretProviderClass

### ISSUE THREAD

**Issue by manisha-tanwar** [bjw-s/helm-charts#333]
# Details

**Add support for secretProviderClass:**

We use azure vault with aks and use secretProviderClass heavily and as app-template doesn't support it I'm having issues using it.

It would be great if it provides something like this in `values.yaml`

```
 secretProviderClass:
  enabled: true
  parameters:
    resourceGroup: ""
    keyvaultName: ""
  secretobjects:
    - objectName: test
      objectType: secret  # object types: secret, key or cert
      envVarName: "" # Set 'envVarName' to include the secret as an environment variable. Omit if it should be filesystem mounted only.
```

Reference:
https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/release-1.0/test/bats/tests/vault/vault_v1_secretproviderclass.yaml
