### ISSUE TITLE
probes don't allow exec types

### ISSUE THREAD

**Issue by disconn3ct** [bjw-s/helm-charts#337]
https://github.com/bjw-s/helm-charts/blob/040eb7b9d2d831272c0c3daa249d7e19a4dee38d/charts/library/common/schemas/containers.json#L187 is much more limited than https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-liveness-command

```yaml
probes:
  startup:
    custom: true
    type: exec
    spec:
      command:
        - sh
        - -c
        - test -f /shared/readyNow
      initialDelaySeconds: 0
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3
```
> - controllers.main.containers.containername.probes.startup.type: controllers.main.containers.containername.probes.startup.type must be one of the following: "TCP", "HTTP", "HTTPS", "AUTO"

**Comment by disconn3ct** [comment]
FYI anyone who hits this can work around with patches:
```yaml
kind: HelmRelease
spec:
  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: Deployment
              name: whatever
            patch: |-
              - op: add
                path: /spec/template/spec/containers/0/startupProbe
                value:
                  exec:
                    command:
                      - sh
                      - -c
                      - test -f /running
                  initialDelaySeconds: 5
  values:
    controllers.main.containers.main.probes.startup.enabled: false
```

**Comment by haraldkoch** [comment]
Your syntax seems to be off. This is taken from a working helmrelease:

```
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      - /usr/sbin/rndc
                      - status
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
```
