### ISSUE TITLE
Allow service setting externalName

### ISSUE THREAD

**Issue by lauer** [bjw-s/helm-charts#339]
# Details

**Add support for service type: ExternalName:**

Example: 
```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: prod
spec:
  type: ExternalName
  externalName: my.database.example.com
```

**Anything else you would like to add:**

This is currently not possible, because of the `externalName` setting is not valid according to the common schema and would not be included in the template

**Additional Information:**

Documentation here: https://kubernetes.io/docs/concepts/services-networking/service/#externalname

**Comment by lauer** [comment]
Thanks for the effort, is there a way to test this implementation in my helm chart? It does not looks like you build beta/unstable charts?

I also tried to add the template-service to my templates dir, but I was not able to fetch all variables from common template, which needs to be used in annotations and labels. Maybe you have an enable for that?

**Comment by bjw-s** [comment]
I'm pushing out 3.3.0 right now and the required app-template (schema) updates after that, so you should be good to use that in a few minutes :)

**Comment by lauer** [comment]
You didn't write a test for this externalName setting. Are you sure it was neigh to add it to the json file?
Because the template generation does not include this. 

```yaml
service:
    main:
      primary: true
      ... snip ...
    api-backend:
      primary: false
      controller: app
      type: ExternalName
      externalName: httpbin.org
      ports: 
        http:
          port: 80
```

returns the following spec

```yaml
spec:
  type: ExternalName
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
```

so without the `externalName`. The schema check does not complain about the field.
