### ISSUE TITLE
Persistent volume mapping naming is incorrect when the persistence name matches the deployment name

### ISSUE THREAD

**Issue by justSem** [bjw-s/helm-charts#345]
# Details

**What steps did you take and what happened:**
I've observed that when making a `persistence` object where the name of the object matches the name of the helmrelease, the pvc is created with solely that name.
In the example below:
```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: pgadmin
  namespace: database
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.3.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    ....
    persistence:
 
      pgadmin:
        enabled: true
        type: persistentVolumeClaim
        size: 128Mi
        storageClass: longhorn
        accessMode: ReadWriteOnce
        globalMounts:
          - path: /var/lib/pgadmin
            readOnly: false
```
it'll result in a pvc named `pgadmin` to be created.
```
k -n database get pvc                             
NAME                            STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   VOLUMEATTRIBUTESCLASS   AGE
pgadmin                         Bound    pvc-1f7904fd-0b4d-4037-947a-c5a6ee44bfab   128Mi      RWO            longhorn       <unset>                 102s
```

However, this will result in the container failing to launch with the error: 
```
Warning  FailedScheduling  90s default-scheduler  0/4 nodes are available: persistentvolumeclaim "pgadmin-pgadmin" not found. preemption: 0/4 nodes are available: 4 Preemption is not helpful for scheduling.
```

When changing the persistence name to `pgadmin4` (for example), the error disappears, because the pvc name is now rendered correctly.

```yaml
    ....
    persistence:
 
      pgadmin4:
        enabled: true
        type: persistentVolumeClaim
        size: 128Mi
        storageClass: longhorn
        accessMode: ReadWriteOnce
        globalMounts:
          - path: /var/lib/pgadmin
            readOnly: false
```

```
k -n database get pvc
NAME                            STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   VOLUMEATTRIBUTESCLASS   AGE
pgadmin-pgadmin4                Bound    pvc-757018da-1d1c-4ff2-9777-1bf0891a4c03   128Mi      RWO            longhorn       <unset>                 6m31s
```

```
  Normal   SuccessfulAttachVolume  2s    attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-757018da-1d1c-4ff2-9777-1bf0891a4c03"
```

Perhaps I've overlooked something, or perhaps this is intended behavior. I couldn't really find anything on it, hence the bug report :)
