### ISSUE TITLE
Document mounting files from configmaps

### ISSUE THREAD

**Issue by p4block** [bjw-s/helm-charts#348]
# Details
I wanted to mount a configmap I setup on the chart's values. This was more or less straightforward, but I had a major pain point. 

The first is that I couldn't mount a file in the configmap to /config.yml, in an obvious way, it would cause an empty container that didn't start (makes sort of sense)

I resorted to mounting it to a subfolder
```
persistence:
  configyml:
    enabled: true
    type: configMap
    identifier: configyml
    advancedMounts:
      main:
        main:
          - path: /app

```
This generates /app/config.yml correctly, but the entire /app is read only and whichever was on the container also happens to get nuked out of existence.

I must be doing something wrong :sweat_smile: 

Thanks a lot for maintaining this chart!
