### ISSUE TITLE
Argocd complains about hostUsers being a different value than what is returned by kubectl

### ISSUE THREAD

**Issue by halkeye** [bjw-s/helm-charts#366]
# Details

**What steps did you take and what happened:**

1. Upgraded to 3.6.0
2. Argocd has started complain that hostUsers is out of sync on deployments.

**What did you expect to happen:**

Not adding the field unless its enabled (feature or value)

**Anything else you would like to add:**

argocd essentially does a kubectl get and compares the results.

**Additional Information:**

Original PR: https://github.com/bjw-s/helm-charts/pull/363

According to https://kubernetes.io/docs/tasks/configure-pod-container/user-namespaces/ the new feature is gated and the gate isn't enabled by default

**Work around:**

1. Add ignoreDifferences at application level
```
      ignoreDifferences:
        - group: "apps"
          kind: Deployment
          jqPathExpressions:
            - .spec.template.spec.hostUsers
```
2. Add it to global cm config (i hope this one works, my tests say it should, but its new to me)
```
resource.customizations.ignoreDifferences.apps_Deployment: |
  jqPathExpressions:
    - .spec.template.spec.hostUsers
````
