### ISSUE TITLE
serviceMonitor:'s endpoint doesn't support templated secrets

### ISSUE THREAD

**Issue by halkeye** [bjw-s/helm-charts#367]
# Details

I would like to be able to use Templated secret names in the basic auth so i can use the chart's name as a prefix for the secrets that are created by app-templates.secrets

Example
```
serviceMonitor:
     app:
       serviceName: app
       endpoints:
         - port: http
           scheme: http
           path: /api/v1/metrics
           interval: 1m
           scrapeTimeout: 10s
           basicAuth:
              username:
               name: "{{.Release.Name}}-secret"
               key: VIKUNJA_METRICS_USERNAME
             password:
               name: "{{.Release.Name}}-secret"
               key: VIKUNJA_METRICS_PASSWORD
```
