### ISSUE TITLE
Allow enabled: false for containers

### ISSUE THREAD

**Issue by runningman84** [bjw-s/helm-charts#373]
# Details

Sometimes you would like to specify some sidecar container which can be easily enabled or disabled, therefore it would be cool to have the option to set enabled: false to disable it (default should be true). 

This used to work similar in the past with addon containers which could be enabled or disabled... (for example vscode)

**Describe the solution you'd like:**

````
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/home-assistant/home-assistant
              tag: 2024.12.5
            env:
              TZ: "Europe/Berlin"
              PYTHONPATH: "/config/deps"
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              limits:
                memory: 1024Mi
              requests:
                cpu: 200m
                memory: 512Mi
          codeserver:
            enabled: false
            image:
              repository: codercom/code-server
              tag: 4.96.2
            args:
              - --user-data-dir
              - "/config/.vscode"
              - --auth
              - "none"
            resources:
              limits:
                memory: 512Mi
              requests:
                cpu: 250m
                memory: 512Mi
            volumeMounts:
              - name: config
                mountPath: /config
````

**Anything else you would like to add:**

**Additional Information:**
