### ISSUE TITLE
RBAC-related Helm template error when deploying with `app-template`

### ISSUE THREAD

**Issue by barthofu** [bjw-s/helm-charts#389]
**Description:**
I encountered an issue while tempting a migration from the the `app-template` Helm chart `v3.2.1` to `v3.7.1` on a previously working deployment. I deploy it as a subchart in my Helm deployment. The error appears to be related to the `rbac.roles` values not being defined.

**Error Message:**
```sh
Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = failed to execute helm template command: failed to get command args to log: `helm template . --name-template music --namespace music --kube-version 1.29 --include-crds` failed exit status 1:
Error: template: music/charts/navidrome/templates/common.yaml:14:3: executing "music/charts/navidrome/templates/common.yaml" at <include "bjw-s.common.loader.generate" .>: error calling include: template: music/charts/beets/charts/common/templates/loader/_generate.tpl:21:6: executing "bjw-s.common.loader.generate" at <include "bjw-s.common.render.rbac" .>: error calling include: template: music/charts/beets/charts/common/templates/render/_rbac.tpl:6:6: executing "bjw-s.common.render.rbac" at <include "bjw-s.common.render.rbac.roles" (dict "rootContext" $rootContext)>: error calling include: template: music/charts/beets/charts/common/templates/render/_rbac.tpl:18:39: executing "bjw-s.common.render.rbac.roles" at <$rootContext.Values.rbac.roles>: nil pointer evaluating interface {}.roles
```

**Helm Chart Used:**
```yaml
- alias: beets
  name: app-template
  repository: https://bjw-s.github.io/helm-charts
  version: 3.7.1
```

**Values.yaml Configuration:**
```yaml
beets:
  global:
    nameOverride: beets

  defaultPodOptions:
    nodeSelector:
      kubernetes.io/hostname: "worker-1"
    securityContext:
      fsGroup: 1000
      fsGroupChangePolicy: "OnRootMismatch"

  controllers:
    main:
      replicas: 1
      containers:
        main:
          image:
            repository: linuxserver/beets
            tag: 2.2.0
          tty: true
          env:
            PUID: 1000
            PGID: 1000
            TZ: Europe/Paris
          securityContext:
            runAsUser: 0
            runAsGroup: 0

  service:
    main:
      controller: main
      type: ClusterIP
      ports:
        http:
          port: 8337

  ingress:
    main:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: letsencrypt-issuer
      hosts:
        - host: &host "beets.home.bartho.dev"
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: http
      tls:
        - secretName: beets-tls
          hosts:
            - *host

  persistence:
    data:
      existingClaim: pvc-music-beets-config
      globalMounts:
        - path: /config
    music:
      existingClaim: pvc-smb-music-medias
      globalMounts:
        - path: /music
          subPath: music
    downloads:
      existingClaim: pvc-smb-music-torrents
      globalMounts:
        - path: /downloads
          subPath: music
```

**Analysis:**
It looks like the `rbac.roles` key is missing from `values.yaml`, leading to a `nil pointer` error when Helm tries to render the `_rbac.tpl` template. This error suggests that the chart assumes `rbac.roles` is always defined, even when RBAC is not explicitly configured.

Would love to get insights on the best approach to understand and fix this!

**Environment Details:**
- **Kubernetes Version:** v1.29.3 (`k3s`)
- **Chart Version:** v3.7.1
- **Deployment Method:** ArgoCD

Let me know if you need more details! 🚀
