### ISSUE TITLE
app-template: imagePullSecret ignores namespace

### ISSUE THREAD

**Issue by chrede88** [bjw-s/helm-charts#395]
# Details

Adding `imagePullSecrets` to the chart referencing a secret in a different namespace is not working correctly. The namespace is ignored.

This is what I did:
```yaml
defaultPodOptions:
  imagePullSecrets:
    - name: ghcr-pull-secret
      namespace: external
```

The flux-local output of the rendered `deployment` also shows the namespace. See this PR: https://github.com/chrede88/home-ops/pull/524

But when I check the actual deployed manifests the namespace is missing.
```yaml
spec:
  template:
    spec:
      imagePullSecrets:
      - name: ghcr-pull-secret
```
