### ISSUE TITLE
Chart does not build with latest versions of Kustomize and ValuesInLine since Kustomize 5.4.2

### ISSUE THREAD

**Issue by David-Igou** [bjw-s/helm-charts#397]
# Details

Kustomize 5.4.2 [introduced a bug (or behavior? Not a lot of discussion)](https://github.com/kubernetes-sigs/kustomize/issues/5720) where charts with an empty values.yaml fail to build using the valuesInLine parameter with the error: `Error: could not parse values file into rnode: EOF`

So for example, this fails to build with `kustomize build --enable-helm`:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
helmCharts:
- name: app-template
  releaseName: mktxp-exporter
  namespace: monitoring
  version: 3.7.3
  repo: https://bjw-s.github.io/helm-charts
  valuesInline:
    defaultPodOptions:
      securityContext:
[etc]
```

**What did you expect to happen:**

I expected the manifests to build

**Anything else you would like to add:**

As stated in the issue, this can be worked around by the upstream values.yaml to have any key value pair present (so even if its contents is `foo: bar`), or have the "dummy" values.yaml present in the downstream repo along with valuesInLine, ie:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
helmCharts:
- name: app-template
  releaseName: mktxp-exporter
  namespace: monitoring
  version: 3.7.3
  repo: https://bjw-s.github.io/helm-charts
  valuesFile: values.yaml
  valuesInline:
    defaultPodOptions:
      securityContext:
[etc]
```

Contents of values.yaml:

```yaml
foo: bar
```

**Additional Information:**

A ridiculous workaround is that you can also set `valuesFile: kustomization.yaml` and things will build without the need to write a new file
