### ISSUE TITLE
[FR] Add Horizontal Pod Autoscaling to Common Chart

### ISSUE THREAD

**Issue by jacaudi** [bjw-s/helm-charts#401]
# Details

**Describe the solution you'd like:**

I would like to an option to configure HPA for deployments and statefulsets. I would like to start with metrics server based metrics and iterate other sources later.  

**Anything else you would like to add:**

I would like to collaborate with you and find the best way to implement this. I just need to know if you would like me to wait until the 4.0.0 release, or if you want to add it to the 4.0.0 release. Thank you!

**Additional Information:**

Each HPA configuration would be specific to each controller. Maybe something like this:

```
controllers:
  example:
    type: statefulset
    hpa:
      min: 1
      max: 10
      metrics:
        - cpu
          utilization: 50
        - memory
           utilization: 80
    containers:
      example:
        image:
```
