### ISSUE TITLE
Option to create a PVC per replicated pod

### ISSUE THREAD

**Issue by jacaudi** [bjw-s/helm-charts#402]
# Details

**Describe the solution you'd like:**

I would like to be able to set an option that creates a PVC per replicated pod within a a controller. For example, I would like to be able to run my ArchiveTeam pod as a DaemonSet, and have it set to give each pod its own PVC attached to it.   

**Anything else you would like to add:**

I am happy to also collaborate on this request as well! 

**Additional Information:**

Nope, but I would like to thank you for an awesome chart!

**Comment by joryirving** [comment]
Would it not make more sense to run it as an STS? That way it should create a PVC per-pod, if you're using the chart to define that PVC.

**Comment by jacaudi** [comment]
STS? My brain keeps defaulting to AWS's STS and I know that's not what you are talking about 😆

**Comment by joryirving** [comment]
Statefulset.
Something like [this](https://github.com/chkpwd/iac/blob/ff34d98d1c4cd684d6c2e1dd3cdf9ba412a34ae0/kubernetes/apps/sonarr/helm-release.yml#L36-L47):
```yaml
        statefulset:
          volumeClaimTemplates:
            - name: config
              accessMode: ReadWriteOnce
              size: "${VOLSYNC_CAPACITY}"
              storageClass: ceph-block
              dataSourceRef:
                kind: ReplicationDestination
                apiGroup: volsync.backube
                name: "${APP}"
              globalMounts:
                - path: /config
```
