### ISSUE TITLE
Add `persistentVolumeClaimRetentionPolicy` to statefulset configuration

### ISSUE THREAD

**Issue by jacaudi** [bjw-s/helm-charts#403]
# Details

**Describe the solution you'd like:**

Please add the ability to add `persistentVolumeClaimRetentionPolicy` to be able to control when/if PVCs created by the statefulset are deleted. This feature went stable on K8S v1.32

**Anything else you would like to add:**

```
apiVersion: apps/v1
kind: StatefulSet
...
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Delete
...
```

**Additional Information:**

https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#persistentvolumeclaim-retention

**Comment by jacaudi** [comment]
Ugh, I feel like an idiot. 🤦🏻 

```
        statefulset:
          volumeClaimTemplates:
            - name: cache
              accessMode: ReadWriteOnce
              size: 240Gi
              storageClass: cephblock
              globalMounts:
                - path: /var/lib/buildkit
          persistentVolumeClaimRetentionPolicy:
            whenDeleted: Delete
            whenScaled: Delete
```

This works perfectly the second time I applied it. The first was improperly formatted.
