### ISSUE TITLE
Code Server git deployKeySecret has permissions ug+r instead of just u+r

### ISSUE THREAD

**Issue by szinn** [bjw-s/helm-charts#43]
# Details

When using the code server add-on in app-template, the defaultMode is specified as 256 and perhaps should actually be 100 (hex vs decimal?)

```
    addons:
      codeserver:
        enabled: true
        image:
          repository: codercom/code-server
          tag: 4.7.0
        workingDir: "/config"
        git:
          deployKeySecret: home-assistant-code-server
```

```
root@home-assistant-7647895d87-j8jvn:~/.ssh# ls -l
total 4
-r--r----- 1 root coder 3434 Sep 12 01:04 id_rsa
```

**What steps did you take and what happened:**

**What did you expect to happen:**

Permissions should just be u+r

**Anything else you would like to add:**

**Additional Information:**
