### ISSUE TITLE
Feature Request: support arbitrary kubernetes resources in values

### ISSUE THREAD

**Issue by gclawes** [bjw-s/helm-charts#56]
# Details

**Describe the solution you'd like:**

Some applications from `k8s-at-home` like [`radarr`](https://github.com/k8s-at-home/charts/tree/master/charts/stable/radarr/templates) had additional resources beyond what the common chart provided.  It would be useful to be able to specify extra resources like this directly in the values for app-templates.

The [bedag/raw](https://github.com/bedag/helm-charts/tree/master/charts/raw) chart provides a good model for doing this.  The values `.Values.resources` and `.Values.templates` are provided as arrays of kubernetes resource objects that are rendered into the helm chart, with templates rendered with the [`tpl` function](https://github.com/bedag/helm-charts/blob/master/charts/raw/templates/resources.yaml#L24).

Because `resources` is already a reserved value in the top level of `app-template`, I propose `.Values.extraManifests` and `.Values.extraManifestTemplates` (though if anyone wants to propose something better, go for it).

**Additional Information:**
Links:
https://github.com/bedag/helm-charts/tree/master/charts/raw
https://artifacthub.io/packages/helm/main/raw

The `bedag/raw` template is licensed under [`Apache-2.0`](https://github.com/bedag/helm-charts/blob/master/LICENSE)

**Comment by onedr0p** [comment]
I could see this being useful for rendering out custom resources. For example, you could create a helm chart that only applies `ClusterIssuers` from cert-manager.

Take a `HelmRelease` for cert-manager for example:

```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 15m
  chart:
    spec:
      chart: cert-manager
      version: v1.10.0
      sourceRef:
        kind: HelmRepository
        name: jetstack-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    installCRDs: true
```

You could then apply the `ClusterIssuer` CR in a `HelmRelease` that depends on the cert-manager helm release:

```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app cert-manager-issuers
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 0.2.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  values:
    customResource:
		 - apiVersion: cert-manager.io/v1
			kind: ClusterIssuer
			metadata:
			  name: letsencrypt-production
			spec:
			  acme:
			    server: https://acme-v02.api.letsencrypt.org/directory
			    email: "${SECRET_EMAIL}"
			    privateKeySecretRef:
			      name: letsencrypt-production
			    solvers:
			      - dns01:
			          cloudflare:
			            email: "${SECRET_EMAIL}"
			            apiKeySecretRef:
			              name: cloudflare-token-secret
			              key: cloudflare-token
			        selector:
			          dnsZones:
			            - "${SECRET_PUBLIC_DOMAIN}"
```

I know this is absolutely insane idea 🤣
