### ISSUE TITLE
RFC: Option to enable a pre-upgrade helm hook that is able to snapshot the config PVC via a job

### ISSUE THREAD

**Issue by onedr0p** [bjw-s/helm-charts#77]
# Details

**Describe the solution you'd like:**

An option to enable a `pre-upgrade` helm hook that is able to snapshot the config PVC via a Kubernetes Job with the external-snapshotter.

---

For example this job would get ran before helm upgrade:

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      containers:
      - name: snapshot-volume
        image: "bjw-s/snapshotter:1.0.0"
        command: ["run","snapshot"]
```

---

Maybe it could be enabled via a new option with an array of volumes for the Job to be ran for:

```yaml
values:
  snapshotHooks:
    - volume: config
    - volume: test
```

Or, included in persistence and volumeClaimTemplates blocks:

```yaml
values:
  persistence:
    config:
      enabled: true
      existingClaim: config
      snapshotBeforeUpgrade: true
```

```yaml
values:
  volumeClaimTemplates:
    - name: config
      mountPath: /config
      accessMode: ReadWriteOnce
      size: 10Gi
      storageClass: ceph-block
      snapshotBeforeUpgrade: true
      labels:
        snapshot.home.arpa/enabled: "true"
```

---

Having something like this would make reverting back to a previous version of an application with the matching data volume given you change your PVC to the snapshot taken via `dataSource`

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: restore-pvc-1
spec:
  # ...
  dataSource:
    name: snapshot-name
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
```

---

Few areas of concern I have are:
* The container in the job needs to have access to either snapshot via kubectl or another method.
* The external snapshotter and CRDs need to be installed before this is enabled, we could probably check that it's in the cluster with `Capabilities` via helm
