### ISSUE TITLE
ServiceAccount does not work with 1.25+

### ISSUE THREAD

**Issue by onedr0p** [bjw-s/helm-charts#78]
# Details

Using the following config on Kubernetes 1.25 does not adhere to the changes made to ServiceAccounts in 1.25

```yaml
values:
  serviceAccount:
    create: true
    name: *app
```

In 1.25 we need to define the Secret and link it to the SA:

```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
secrets:
  - name: vault-auth
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: vault-auth
  annotations:
    kubernetes.io/service-account.name: vault-auth
```
