### ISSUE TITLE
cephfs mount

### ISSUE THREAD

**Issue by andim202** [bjw-s/helm-charts#83]
# Details

**Describe the solution you'd like:**

Hi! It would be very handy to not only mount `pvc, emptyDir, hostPath and nfs` within the `persistence` section but also `ceph`.
As of the [docs](https://kubernetes.io/docs/concepts/storage/volumes/#cephfs) it does not need a lot of configuration expect the `monitors` on which the ceph-storage is running.

At the end, it would be nice to configure it in the `values.yaml` as the following:

```YAML
persistence:
   cephfs-config:
     enabled: true
     type: cephfs
     monitors:
      - mon.rook.svc.cluster.local:6790
      - mon.rook.svc.cluster.local:6789
     path: /registryFS
     secretRef:
       name: rook-rbd-user
```

**Anything else you would like to add:**

If there is no intention to add this, I can create a PR and try to implement it. I am relatively new to k8s, helm and everything but would put in the effort to create the PR properly.

Thanks in advance!
