### ISSUE TITLE
RBAC

### ISSUE THREAD

**Issue by djessich** [bjw-s/helm-charts#96]
Please provide support for RBAC creation.

**Comment by onedr0p** [comment]
Please provide more information and an example helm values of what you would like to see.

**Comment by djessich** [comment]
Example manifest:

```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: diun
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - watch
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: diun
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: diun
subjects:
  - kind: ServiceAccount
    name: diun
    namespace: diun
```

Helm config for above:

```
rbac:
  main:
    enabled: true
    clusterRoleLabels: {}
    clusterRoleAnnotations: {}
    clusterRoleBindingLabels: {}
    clusterRoleBindingAnnotations: {}
    rules:
      apiGroups:
        - ''
      resources:
        - pods
      verbs:
        - get
        - watch
        - list
    # automatically created from serviceAccountName
    #    serviceAccountName:
    # Add subjects to the ClusterRoleBinding. Includes the above created serviceAccount
    #   subjects: {}
```

For reference see TrueCharts library-chart, how this could be done.
