### ISSUE TITLE
Additional examples (additionalContainers)

### ISSUE THREAD

**Issue by ahgraber** [bjw-s/helm-charts#98]
# Details

**Describe the solution you'd like:**

I frequently would like to add an additionalContainer (webserver, etc) to a deployment, but it's not clear to me how the additionalContainer objects map.  If I wanted to define an additional container image/tag, environmental variables, attach secrets/configmaps, and include a service,  how can I define all that in the additionalContainers object? Do some things (i.e., services(?) get defined with the main image?  

An example would go a long way to helping sort this out.

**Anything else you would like to add:**

Chart is incredibly useful -- thank you!

**Comment by onedr0p** [comment]
Here's an example I use, anything passed into `additionalContainers` is a standard kubernetes containers object.

```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bazarr
  namespace: default
spec:
# ...
  values:
# ...
    additionalContainers:
      subcleaner:
        name: subcleaner
        image: k8s.gcr.io/git-sync/git-sync:v3.6.2
        args:
          - --repo=https://github.com/KBlixt/subcleaner.git
          - --branch=master
          - --depth=1
          - --root=/add-ons/subcleaner
        volumeMounts:
          - name: add-ons
            mountPath: /add-ons
# ...
```
